## you probably need to change or comment/uncomment some of these
#
# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
#
# tab delimited samples file ... should have the following 3 columns
# sampleName	path_to_R1_fastq	path_to_R2_fastq
#
samples: "WORKDIR/samples.tsv"
#
# Should the CLEAR pipeline be run? True or False WITHOUT quotes
run_clear: True
#
# Should the DCC pipeline be run? True or False WITHOUT quote
run_dcc: True
#
# Should the MapSplice pipeline be run? True or False WITHOUT quotes
run_mapsplice: False
mapsplice_min_map_len: 50
mapsplice_filtering: 2  # 1=less stringent 2=default
#
# Should the circRNA_finder  be run? True or False WITHOUT quotes
run_circRNAFinder: True
# Should the NCLscan pipeline be run? True or False WITHOUT quotes
# This can only be run for PE data
run_nclscan: False
nclscan_config: "WORKDIR/nclscan.config"
#
# Should we also run find_circ? True or False WITHOUT quotes
run_findcirc: True



# select references .... host + viruses(comma-separated):
# select host: # options are hg38 or mm39
# host:       "hg38"
# additives:  "ERCC" # options are ERCC and BAC16Insert
# viruses:    "NC_009333.1"
host:       "HOST"
additives:  "ADDITIVES"
viruses:    "VIRUSES"
# select viruses and other (ERCC/BAC): options are
# ERCC
# BAC16Insert
# 
# | RefSeq  Sequence | RefSeq assembly accession | Notes                                                 |
# | ---------------- | ------------------------- | ----------------------------------------------------- |
# | NC_007605.1      | GCF_002402265.1           | Human gammaherpesvirus 4 (Epstein-Barr virus)         |
# | NC_000898.1      | GCF_000846365.1           | Human betaherpesvirus 6B                              |
# | NC_001664.4      | GCF_000845685.2           | Human betaherpesvirus 6A                              |
# | NC_001716.2      | GCF_000848125.1           | Human betaherpesvirus 7                               |
# | NC_006273.2      | GCF_000845245.1           | Human betaherpesvirus 5                               |
# | NC_009333.1      | GCF_000838265.1           | Human gammaherpesvirus 8                              |
# | NC_045512.2      | GCF_009858895.2           | Severe acute respiratory syndrome-related coronavirus |
# | MN485971.1       | xx                        | HIV from Belgium ... GTF is hand curated              |
#
#   | RefSeq  Sequence | RefSeq assembly accession | Notes                                                        |
#   | ---------------- | ------------------------- | ------------------------------------------------------------ |
#   | NC_001806.2      | GCF_000859985.2           | [Human alphaherpesvirus 1 (Herpes simplex virus type 1)](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=10298&lvl=3&lin=f&keep=1&srchmode=1&unlock) (strain 17) |
#
#  | RefSeq  Sequence | RefSeq assembly accession | Notes                                                        |
#  | ---------------- | ------------------------- | ------------------------------------------------------------ |
#  | KT899744.1       | KT899744.1                | HSV-1 strain KOS                                             |
#  | MH636806.1       | MH636806.1                | MHV68 (Murine herpesvirus 68 strain WUMS)                    |
#
# comma separated list
# STAR 1-pass junction filtering....
# 1st pass of STAR generates a list of splice junctions which are filtered to be parsed to the second pass of STAR
# Separate filters can be applied to the "host"+"additives" and "viruses" defined above
# Typically, since "host"+"additives" annotations are much more well-established we filter out noncanonical and unannotated
# while keeping everything for the poorly annotated viruses
star_1pass_filter_host_noncanonical: "True"
star_1pass_filter_host_unannotated: "True"
star_1pass_filter_viruses_noncanonical: "False"
star_1pass_filter_viruses_unannotated: "False"

# BSJ filters in bp:
minsize_host: 150
minsize_virus:  150
maxsize_host: 1000000000
maxsize_virus:  5000


#
## Resources
#
## hg38 vanilla --> hg38 rRNA masked + rRNA appended
##
#ref_fa: "/data/CCBR_Pipeliner/Pipelines/resources/CCBR_circRNA_DAQ/hg38/hg38_rRNA_masked_plus_rRNA.fa"
#ref_gtf: "/data/CCBR_Pipeliner/Pipelines/resources/CCBR_circRNA_DAQ/hg38/hg38_rRNA_masked_plus_rRNA.gtf"
#regions: "/data/CCBR_Pipeliner/Pipelines/resources/CCBR_circRNA_DAQ/hg38/hg38_rRNA_masked_plus_rRNA.fa.regions"
#star_index_dir: "/data/CCBR_Pipeliner/Pipelines/resources/CCBR_circRNA_DAQ/hg38/STAR_index_no_GTF_2.7.6a"
#ref_bwa_index: "/data/CCBR_Pipeliner/Pipelines/resources/CCBR_circRNA_DAQ/hg38/hg38_rRNA_masked_plus_rRNA"
#ref_hisat_index: "/data/CCBR_Pipeliner/Pipelines/resources/CCBR_circRNA_DAQ/hg38/hg38_rRNA_masked_plus_rRNA"
#ref_bowtie1_index: "/data/CCBR_Pipeliner/Pipelines/resources/CCBR_circRNA_DAQ/hg38/hg38_rRNA_masked_plus_rRNA"
#genepred_w_geneid: "/data/CCBR_Pipeliner/Pipelines/resources/CCBR_circRNA_DAQ/hg38/hg38_rRNA_masked_plus_rRNA.genes.genepred_w_geneid"
#
# hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC
# * hg38 ... rRNA masked
# * rRNA ... 45S and 5S sequences
# * ERCC sequences
# * viruses:



# ref_fa: "/data/Ziegelbauer_lab/resources/mm39_ERCC_HSV1_MHV68/mm39_ERCC_HSV1_MHV68.fa"
# ref_gtf: "/data/Ziegelbauer_lab/resources/mm39_ERCC_HSV1_MHV68/mm39_ERCC_HSV1_MHV68.gtf"
# regions: "/data/Ziegelbauer_lab/resources/mm39_ERCC_HSV1_MHV68/mm39_ERCC_HSV1_MHV68.regions"
# star_index_dir: "/data/Ziegelbauer_lab/resources/mm39_ERCC_HSV1_MHV68/STAR_index_no_GTF_2.7.6a"
# ref_bwa_index: "/data/Ziegelbauer_lab/resources/mm39_ERCC_HSV1_MHV68/mm39_ERCC_HSV1_MHV68"
# ref_hisat_index: "/data/Ziegelbauer_lab/resources/mm39_ERCC_HSV1_MHV68/mm39_ERCC_HSV1_MHV68"
# ref_bowtie1_index: "/data/Ziegelbauer_lab/resources/mm39_ERCC_HSV1_MHV68/mm39_ERCC_HSV1_MHV68"
# genepred_w_geneid: "/data/Ziegelbauer_lab/resources/mm39_ERCC_HSV1_MHV68/mm39_ERCC_HSV1_MHV68.genes.genepred_w_geneid"


#



## you most probably dont need to change these
scriptsdir: "PIPELINE_HOME/workflow/scripts"
resourcesdir: "PIPELINE_HOME/resources"
tools: "PIPELINE_HOME/resources/tools.yaml"
# default cluster
# cluster: "PIPELINE_HOME/resources/cluster.json"
cluster: "WORKDIR/cluster.json"
adapters: "PIPELINE_HOME/resources/TruSeq_and_nextera_adapters.consolidated.fa"
circexplorer_bsj_circRNA_min_reads: 2 # in addition to "known" and "low-conf" circRNAs identified by circexplorer, we also include those found in back_spliced.bed file but not classified as known/low-conf only if the number of reads supporting the BSJ call is greater than this number
minreadcount: 2 # this is used to filter circRNAs while creating the per-sample counts table
flanksize: 18 # 18bp flank on either side of the BSJ .. used by multiple BSJ callers
ciri_perl_script: "/data/Ziegelbauer_lab/tools/CIRI_v2.0.6/CIRI2.pl"
nclscan_dir: "/data/Ziegelbauer_lab/tools/NCLscan-1.7.0"
circrnafinder_dir: "/data/Ziegelbauer_lab/tools/circRNA_finder-1.2"
find_circ_dir: "/data/Ziegelbauer_lab/tools/find_circ"
dcc_strandedness: "-ss" # "-ss" for stranded library and "--nonstrand" for unstranded
cutadapt_min_length: 15
cutadapt_n: 5
cutadapt_max_n: 0.5
cutadapt_O: 5
cutadapt_q: 20
fastas_gtfs_dir: "/data/Ziegelbauer_lab/resources/fastas_gtfs"
annotation_lookups:
  hg38: "PIPELINE_HOME/resources/hg38_2_hg19_lookup.txt"
  mm39: "PIPELINE_HOME/resources/mm39_circBase_annotation_lookup.txt"
