## you most probably dont need to change these
tools: "config/tools.yaml"
star_index_dir: "/data/Ziegelbauer_lab/circRNADetection/resources/STAR_index_no_GTF"
hg38_plus_virusus_fa: "/data/Ziegelbauer_lab/circRNADetection/resources/hg38_plus_viruses.fa"
hg38_plus_virusus_gtf: "/data/Ziegelbauer_lab/circRNADetection/resources/hg38_gencodeV35_plus_viruses.gtf"
hg38_plus_virusus_bwa_index: "/data/Ziegelbauer_lab/circRNADetection/resources/hg38_plus_viruses.fa"
ciri_perl_script: "/data/Ziegelbauer_lab/circRNADetection/resources/CIRI_v2.0.6/CIRI2.pl"
genepred_w_geneid: "/data/Ziegelbauer_lab/circRNADetection/resources/genes.genepred_w_geneid"
reffa: "/data/Ziegelbauer_lab/circRNADetection/resources/hg38_plus_viruses.fa"
#
## you probably need to change or comment/uncomment some of these
#
workdir: "/data/RBL_NCI/ONT/ont_rnaseq/workflow/ONT_RNAseq/test_workdir_1DcDNA"
#
samples: "config/samples.tsv"
