## you probably need to change or comment/uncomment some of these
#
# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
#
# tab delimited samples file ... should have the following 3 columns
# sampleName	path_to_R1_fastq	path_to_R2_fastq
#
samples: "WORKDIR/samples.tsv"
#
# Should the CLEAR pipeline be run? True or False WITHOUT quotes
run_clear: True
#
#
#
#
#
#
#
## you most probably dont need to change these
scriptsdir: "PIPELINE_HOME/scripts"
resourcesdir: "PIPELINE_HOME/resources"
tools: "PIPELINE_HOME/config/tools.yaml"
cluster: "PIPELINE_HOME/config/cluster.json"
adapters: "PIPELINE_HOME/resources/TruSeq_and_nextera_adapters.consolidated.fa"
#
## Resources
#
# hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC
#
ref_fa: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.fa"
ref_gtf: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.gtf"
regions: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.fa.regions"
star_index_dir: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC/STAR_index_no_GTF_2.7.6a"
ref_bwa_index: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC"
ref_hisat_index: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC"
ref_bowtie1_index: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC"
genepred_w_geneid: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.genes.genepred_w_geneid"
#
ciri_perl_script: "/data/Ziegelbauer_lab/tools/CIRI_v2.0.6/CIRI2.pl"
#
# 2 separate filters are applied to junctions reported by STAR 1st pass
# star1passfilter1regions defines regions from the "regions" file to which filter1 will be applied
# filter2 will be applied to all other regions
# filter1: generally, remove duplicates, remove non-canonical, remove unannotated --> applied to host
# filter2: generally, remove duplicates only --> applied to viruses
# True or False WITH quotes
star1passfilter1regions: "hg38,rRNA,ERCC"
star1passfilter1_noncanonical: "True"
star1passfilter1_unannotated: "True"
star1passfilter2_noncanonical: "False"
star1passfilter2_unannotated: "False"
