containers:
  base: "docker://nciccbr/ccbr_ubuntu_base_20.04:v6"
  bowtie1: "docker://nciccbr/charlie_bowtie1:v0.1.1"
  circexplorer: "docker://nciccbr/ccbr_circexplorer:v1.0"
  circRNA_finder: "docker://nciccbr/charlie_circrna_finder:v1.0.1"
  ciri: "docker://nciccbr/charlie_ciri2:v1.0.1"
  clear: "docker://nciccbr/ccbr_clear:v2.0.1"
  cutadapt: "docker://nciccbr/charlie_cutadapt_fqfilter:v1.0.1"
  dcc: "docker://nciccbr/charlie_dcc:v0.2.1"
  fastqc: "docker://nciccbr/ccrgb_qctools:v4.0"
  mapsplice: "docker://cgrlab/mapsplice2:latest"
  multiqc: "docker://nciccbr/ccbr_multiqc_1.15:v1"
  picard: "docker://nciccbr/ccbr_picard_2.27.5:v1"
  R: "docker://nciccbr/ccbr_r_4.3.0:v1"
  star: "docker://nciccbr/ccbr_star_2.7.6a:latest"
  star_ucsc_cufflinks: "docker://nciccbr/charlie_star_ucsc_cufflinks:v0.4.1"
