bwa:
 version: "bwa/0.7.17"
circexplorer:
 version: "circexplorer2/2.3.5"
cutadapt:
 version: "cutadapt/1.18"
fastqc:
 version: "fastqc/0.11.9"
samtools:
 version: "samtools/1.11"
star:
 version: "STAR/2.7.6a"
 alignTranscriptsPerReadNmax: "20000"

