name: LINT

on:
  push:
    branches:
      - activeDev
      - main
      - feature/issue57
  pull_request:
    branches_ignore: []

jobs:
  Dryrun_Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://snakemake/snakemake:v5.24.2
    - name: Lint workflow
      continue-on-error: true
      run: |
              docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 snakemake --lint --snakefile /opt2/workflow/Snakefile -d /opt2/output || \
        echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'
