run-name: ${{github.actor}} is running LINT on main/master branch

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches-ignore: []

jobs:
  Dryrun_Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        uses: actions/checkout@v3
      - run: |
          git branch -a
          git log | head
          ls -alrth config
          ls -alrth workflow
      - name: Running Lint
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'workflow/Snakefile'
          args: '--lint --configfile config/lint.config.yaml'
