run-name: ${{github.actor}} is running LINT

on:
  push:
    branches:
      - activeDev
      - main
      - feature/issue57
  pull_request:
    branches-ignore: []

jobs:
  Dryrun_Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        uses: actions/checkout@v3
      - run: echo "repo cloned --> ${{github.repository}}"
      - run: echo "github workspace --> ${{github.workspace}}"
      - name: Listing the repo
        run: |
          ls -larth ${{github.workspace}}
      - name: Running Lint
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'workflow/Snakefile'
          args: '--lint --configfile config/lint.config.yaml'
      - run: echo "STATUS --> ${{job.status}}"
