name: LINT

on:
  push:
    branches:
      - activeDev
      - main
      - feature/issue57
  pull_request:
    branches_ignore: []

jobs:
  Dryrun_Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Linting
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: '.'
        snakefile: 'workflow/Snakefile'
        args: '--lint --config config/lint.config.yaml'
